environment: development

http_port: 10000
grpc_port: 10001
auth_secret: "KkUlhrOa6N/MMbFtWul+sWx16Oa1p35YBZEcAujn6B8="

mongodb_uri: "mongodb+srv://codearena:zql285637@cluster0.jaj2oh9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

mysql:
  host: "116.62.204.146"
  port: 3306
  username: "memory"
  password: "WcD7TpjS2yAFzeFB"
  database: "memory"

wechat:
  app_id: "wx0c65a63c4bb9b5a8"
  app_secret: "8e03720e3bfb8fefc249642c94f234cc"

aliyun:
  access_key_id: "LTAI5t8fVhydayenEqVUxFLA"
  access_key_secret: "dPq2PVwbjsFVjRnPbTjMCZCVhjbFoa"
  bucket_name: "zql-lovestory"
  endpoint: "oss-cn-beijing.aliyuncs.com"

logger:
  level: "debug"
  log_path: "log/codearena.log"
  max_size: 10
  max_age: 30
  max_backups: 10
