info:
  contact:
    email: zql46@outlook.com
    name: zuoql
    url: https://echoidf.github.io/mynotes/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CodeArena
  version: "1.0"
paths: {}
swagger: "2.0"
